### ISSUE TITLE
Cannot read property 'addMembership' of null

### ISSUE THREAD

**Issue by gkiko** [gyzerok/nodecast-js#1]
I followed your example in README. When the code is run with `node example.js` it throws exception on `browser.destroy();`

```plain
/Users/gkiko/Desktop/node_modules/nodecast-js/lib/SSDP.js:72
            _this._socket.addMembership(BROADCAST_ADDR);
                         ^
TypeError: Cannot read property 'addMembership' of null
    at Socket.<anonymous> (/Users/gkiko/Desktop/node_modules/nodecast-js/lib/SSDP.js:72:26)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at startListening (dgram.js:139:10)
    at dgram.js:230:7
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```
Am I doing something wrong?

**Comment by gyzerok** [comment]
@gkiko I guess there is a bug in my code. I do not check socket for existence in case of it already destroyed. You can remove destroy call and it would work fine.

Btw, you can call ```browser.getList()``` in  the ```onDevice``` callback to get current list.

**Comment by gyzerok** [comment]
I've corrected example in README
