### ISSUE TITLE
Samsung DLNA doesn't work

### ISSUE THREAD

**Issue by DanielFragaBR** [gyzerok/nodecast-js#5]
I'm trying to use Popcorntime CE and it always returns the same error when trying to discover my TV:

    [6702:0111/053121:INFO:CONSOLE(53)] ""%c[%cERROR%c] TypeError: Cannot read property '1' of null" "color: black;" "color: red;" "color: black;" "TypeError: Cannot read property '1' of null\n    at getFriendlyName (/tmp/.org.chromium.Chromium.vdjBJ0/node_modules/nodecast-js/lib/Browser.js:37:60)\n    at /tmp/.org.chromium.Chromium.vdjBJ0/node_modules/nodecast-js/lib/Browser.js:84:32\n    at /tmp/.org.chromium.Chromium.vdjBJ0/node_modules/nodecast-js/lib/Browser.js:31:13\n    at IncomingMessage.\u003Canonymous\u003E (/tmp/.org.chromium.Chromium.vdjBJ0/node_modules/nodecast-js/lib/Browser.js:22:20)\n    at emitNone (events.js:70:20)\n    at IncomingMessage.emit (events.js:147:7)\n    at _stream_readable.js:891:16\n    at process._tickCallback (node.js:375:11)"", source: app://host/src/app/app.js (53)
    [6702:0111/053121:INFO:CONSOLE(37)] "Uncaught TypeError: Cannot read property '1' of null", source: /tmp/.org.chromium.Chromium.vdjBJ0/node_modules/nodecast-js/lib/Browser.js (37)

I asked on Popcorntime CE github, but nobody replied, so I'm trying here, since it seems related to nodecast-js instead.

Any hints? Thanks.

Ps: if you need more information, just ask.

**Comment by gyzerok** [comment]
I guess there is an issue in [this line](https://github.com/gyzerok/nodecast-js/blob/master/src/Browser.js#L28).
But even if I fix it you need to rebuild Popcorn Time yourself to solve this since I am not a Popcorn Time developer..

**Comment by DanielFragaBR** [comment]
Thanks for the answer. No problem. I can rebuild it. I can apply a patch and test it if you want ;)

**Comment by gyzerok** [comment]
Sure, you are welcome! There is no tests in the project. So you need to set up all things for this. Thats why you can ignore test if you want to :)

**Comment by DanielFragaBR** [comment]
Ok, I mean, after you fix this, I can test to see if everything is fine ;) Is it a trivial fix? As far as I understand, it is trying to read something from a null value?

**Comment by gyzerok** [comment]
I suppose it's trivial fix. I can garantee that package wont fail in this case again, but cannot garantee it would discover your TV though.
I'll fix it tomorrow and republish this package so you can update and rebuild.

**Comment by DanielFragaBR** [comment]
No problem. Thank you very much!

**Comment by gyzerok** [comment]
@DanielFragaBR I've republished package. You can update it now and test. Notify me please about your results.

**Comment by DanielFragaBR** [comment]
Ok, I updated nodecast-js:

````
$ npm install nodecast-js --save
nodecast-js@0.1.2 node_modules/nodecast-js
├── upnp-mediarenderer-client@0.0.2 (upnp-device-client@0.0.7)
└── castv2-client@0.0.8 (debug@1.0.4, castv2@0.1.6)
````

Then I rebuilt Popcorntime CE, but it returns the same result:

````
[18279:0112/165904:INFO:CONSOLE(53)] ""%c[%cERROR%c] TypeError: Cannot read property '1' of null" "color: black;" "color: red;" "color: black;" "TypeError: Cannot read property '1' of null\n    at getFriendlyName (/tmp/.org.chromium.Chromium.m5uAfN/node_modules/nodecast-js/lib/Browser.js:37:60)\n    at /tmp/.org.chromium.Chromium.m5uAfN/node_modules/nodecast-js/lib/Browser.js:84:32\n    at /tmp/.org.chromium.Chromium.m5uAfN/node_modules/nodecast-js/lib/Browser.js:31:13\n    at IncomingMessage.\u003Canonymous\u003E (/tmp/.org.chromium.Chromium.m5uAfN/node_modules/nodecast-js/lib/Browser.js:22:20)\n    at emitNone (events.js:70:20)\n    at IncomingMessage.emit (events.js:147:7)\n    at _stream_readable.js:891:16\n    at process._tickCallback (node.js:375:11)"", source: app://host/src/app/app.js (53)
[18279:0112/165904:INFO:CONSOLE(37)] "Uncaught TypeError: Cannot read property '1' of null", source: /tmp/.org.chromium.Chromium.m5uAfN/node_modules/nodecast-js/lib/Browser.js (37)
````

Maybe it's an issue specific to Popcorntime and unrelated to nodecast-js?

**Comment by DanielFragaBR** [comment]
Ok, forget the last message. I don't get that error anymore. Now, another error, but it's not related to nodecast-js:

````
[7365:0113/012140:INFO:CONSOLE(53)] ""%c[%cERROR%c] Error: socket hang up" "color: black;" "color: red;" "color: black;" "Error: socket hang up\n    at createHangUpError (_http_client.js:192:15)\n    at Socket.socketCloseListener (_http_client.js:224:23)\n    at emitOne (events.js:80:20)\n    at Socket.emit (events.js:150:7)\n    at TCP.close (net.js:457:12)"", source: app://host/src/app/app.js (53)
[7365:0113/012140:INFO:CONSOLE(125)] "Uncaught Error: socket hang up", source: events.js (125)
````
I'll try to contact the respective developer. Thank you very much!

**Comment by gyzerok** [comment]
@DanielFragaBR you should update to version 1.0.3. I've forgot to rebuild before publishing in 1.0.2 :)
